In [34]:
import pandas as pd
from io import StringIO
data='{"name":"manasi","email":"manasi@gmail.com","job profile":[{"title":"team lead","role":"permanent"}]}'
df=pd.read_json(StringIO(data))

In [35]:
df

     name             email                                  job profile
0  manasi  manasi@gmail.com  {'title': 'team lead', 'role': 'permanent'}

In [36]:
df.to_json()

'{"name":{"0":"manasi"},"email":{"0":"manasi@gmail.com"},"job profile":{"0":{"title":"team lead","role":"permanent"}}}'

In [37]:
df.to_json(orient="index")

'{"0":{"name":"manasi","email":"manasi@gmail.com","job profile":{"title":"team lead","role":"permanent"}}}'

In [38]:
df.to_json(orient="records")

'[{"name":"manasi","email":"manasi@gmail.com","job profile":{"title":"team lead","role":"permanent"}}]'

In [39]:
df=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data",header=None)
df.head(5)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [40]:
df.to_csv("wine.csv")

In [41]:
url='https://www.fdic.gov/bank/individual/failed/banklist.html'
df=pd.read_html(url)
df[0]

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Community Bank and Trust - West Georgia,LaGrange,Georgia,25796,Anchor Bank,"May 1, 2026",10551
1,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
2,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
3,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
4,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
5,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
6,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
7,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
8,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
9,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
10,Silicon Valley Bank,Santa Clara,California,24735,First–Citizens Bank & Trust Company,"March 10, 2023",10539
11,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
12,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
13,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
14,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
15,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
16,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
17,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
18,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
19,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
20,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
21,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528
22,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,Wisconsin,30003,First-Citizens Bank & Trust Company,"May 5, 2017",10527
23,First NBC Bank,New Orleans,Louisiana,58302,Whitney Bank,"April 28, 2017",10526
24,Proficio Bank,Cottonwood Heights,Utah,35495,Cache Valley Bank,"March 3, 2017",10525

In [42]:
import pandas as pd
import requests

url1 = "https://en.wikipedia.org/wiki/Mobile_country_code"

# Add browser headers
headers = {
    "User-Agent": "Mozilla/5.0"
}

# Fetch webpage
response = requests.get(url1, headers=headers)

# Read tables from HTML
df = pd.read_html(response.text, match="Country", header=0)[0]

print(df)

     Mobile country code                                    Country ISO 3166  \
0                    289                                 A Abkhazia    GE-AB
1                    412                                Afghanistan       AF
2                    276                                    Albania       AL
3                    603                                    Algeria       DZ
4                    544  American Samoa (United States of America)       AS
..                   ...                                        ...      ...
247                  452                                    Vietnam       VN
248                  543                        W Wallis and Futuna       WF
249                  421                                    Y Yemen       YE
250                  645                                   Z Zambia       ZM
251                  648                                   Zimbabwe       ZW

                                  Mobile network codes National MNC authority  \
0             List of mobile network codes in Abkhazia                    NaN
1          List of mobile network codes in Afghanistan                    NaN
2              List of mobile network codes in Albania                    NaN
3              List of mobile network codes in Algeria                    NaN
4       List of mobile network codes in American Samoa                    NaN
..                                                 ...                    ...
247        List of mobile network codes in the Vietnam                    NaN
248  List of mobile network codes in Wallis and Futuna                    NaN
249          List of mobile network codes in the Yemen                    NaN
250             List of mobile network codes in Zambia                    NaN
251           List of mobile network codes in Zimbabwe                    NaN

                      Remarks
0    MCC is not listed by ITU
1                         NaN
2                         NaN
3                         NaN
4                         NaN
..                        ...
247                       NaN
248                       NaN
249                       NaN
250                       NaN
251                       NaN

[252 rows x 6 columns]

C:\Users\manas\AppData\Local\Temp\ipykernel_116428\286985200.py:15: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(response.text, match="Country", header=0)[0]

In [43]:
df_excel=pd.read_excel("FINAL450.xlsx")
df_excel.head()

,Unnamed: 0,Questions by Love Babbar:,Unnamed: 2
0,NaN,Youtube Channel: https://www.youtube.com/chann...,NaN
1,NaN,NaN,NaN
2,Topic:,Problem:,Done [yes or no]
3,NaN,NaN,<->
4,Array,Reverse the array,<->

In [44]:
df_excel.to_pickle("df_excel.pkl")
df = pd.read_pickle("df_excel.pkl")

print(df.head())

  Unnamed: 0                          Questions by Love Babbar:  \
0        NaN  Youtube Channel: https://www.youtube.com/chann...
1        NaN                                                NaN
2     Topic:                                          Problem:
3        NaN                                                NaN
4      Array                                  Reverse the array

          Unnamed: 2
0                NaN
1                NaN
2  Done [yes or no]
3                <->
4                <->